### ISSUE TITLE
Neigh gen - parametri dei costruttori 

### ISSUE THREAD

**Issue by mesosbrodleto** [kdd-lab/LORE_sa#1]
Per ristrutturare i vari neighborhood generator ci serve di capire la funzione di ogni parametro. 

Inizierei intanto dalla classe generica, questo è il costruttore:
 
`
     def __init__(self, bb_predict=None,  bb_predict_proba=None, feature_values=None, features_map=None, nbr_features=None, nbr_real_features=None,
                 numeric_columns_index=None, ocr=0.1, encdec: EncDec = None, original_data=None):`

**Comment by rinziv** [comment]
intanto inizio io con un educated guess. Poi  lascio il campo a @francescanaretto se vuole itnerenire.
`bb_predict`: una funzione che fornisce la classe per un array di instanze da classificare (simile al metodo `predict` di scikit)
`bb_predict_proba`: una funzione che fornisce una stima di probabilita' di tutte le classi
`feature_values`: non sono sicurissimo, ma mi pare contenga la lista delle feature (eventualmente dopo l'encoding)
`features_map`: una mappa che associa le features *dopo* l'encoding con le originali *prima* di encoding
`nbr_features`: numero di feaures dopo encoding
`nbr_real_features`: numero di features prima di encoding
`numeric_columns_index`: indice delle colonne con valore numerico (immagino e spero dopo encoding)
`ocr`: one-class ratio la soglia minima da garantire per ogni valore di classe nel neighborhood
`encdec`: la classe di encoding deconding
`original_data`: immagino sia il dataframe originale prima dell'encodign

**Comment by rinziv** [comment]
Dovrebbe essere il vettore con i valori della feature in input (quella dalla quale si genera poi il vicinato).
Qui il punto dove viene utilizzata:
https://github.com/kdd-lab/LORE_sa/blob/83efe3f04b5e8da1714f2f16d34b0c0c6d0141e0/LoreSA/neighgen.py#L62

**Comment by rinziv** [comment]
Pensavo... secondo me il valore della singola instanza (da cui si genera il vicinato) NON dovrebbe essere un argomento del costruttore. Semmai l'argomento del metodo che mi da il vicinato.
per esempio
``` python
neigh_gen = new MyNeighborhoodGenerator(...)
neighborhood = neigh_gen.generate_from(instance)
```

**Comment by mesosbrodleto** [comment]
sì, sono d'accordo. Vediamo di impostarla così.

**Comment by mesosbrodleto** [comment]
> Dovrebbe essere il vettore con i valori della feature in input (quella dalla quale si genera poi il vicinato). Qui il punto dove viene utilizzata:
> 
> https://github.com/kdd-lab/LORE_sa/blob/83efe3f04b5e8da1714f2f16d34b0c0c6d0141e0/LoreSA/neighgen.py#L62

aggiornamento: quel feature_values non contiene il vettore della singola istanza, ma tutto il dataset probabilmente. Questo perché quella riga sceglie un valore a caso tra un vettore di input. Se passo il vettore della singola istanza, self-feture_Values[i] contiene un intero, da cui quindi non si può scegliere un valore a caso.
