### ISSUE TITLE
encoder/decoder: prepare dataset

### ISSUE THREAD

**Issue by mesosbrodleto** [kdd-lab/LORE_sa#3]
La logica di preparazione del dataset va resa più flessibile: l'utente carica il dataset, sceglie quali sono le features da codificare e decide quando e come trasformare il dataset. Prepare_dataset può essere eliminato sia dalla classe dataset, che da EncDec, diventando parte del flusso di lavoro dell'utente stesso.

**Comment by LoSpino87** [comment]
potremmo anche mantenere prepare_dataset dentro DataSet dandogli altri argomenti (encoder, target etcc..) ma resituendo un nuovo oggetto Dataset con le nuove caratteristiche.
Oggetto che poi viene dato in pasto a lorem, già codificato.

**Comment by mesosbrodleto** [comment]
aggiungo qui per praticità:

il prepare_dataset dentro la classe OneHotEncoder è da rivedere totalmente, se non da eliminare. fit_transform è il metodo che si occupa di codificare le colonne del dataset. Attualmente, fit_transform è un wrapper del fit_transform di sklearn.OneHotEncoder

**Comment by rinziv** [comment]
Sono d'accordo nell'eliminare il `prepare_dataset` da `Dataset`. Come discusso stamattina, dividerei in due parti l'analisi del formato dei dati in input.

- Si può inserire un dizionario con la specifica dei descrittori di ogni feataure (questo ovviamente solo per i dati tabulari). Una cosa del tipo: 
`{age: {
  min:10, 
  max:99, 
  mean:45, 
  type:'Q'},
. . . 
}`
- Si può utilizzare una funzione di utility simile a `prepare_dataset` per generare questo descrittore in automatico.

Se questa funzione diventa separata, forse anche la classe `Dataset` potrebbe essere rimossa

**Comment by rinziv** [comment]
Aggiungo anche una specifica più dettagliata per `Encoder`:
```python
class Encoder:
    def encode(self, x):
        """
        Metodo per codificare l'input x.

        Parametri:
        - x: L'input da codificare.

        Restituisce:
        - z: L'output codificato.
        """
        raise NotImplementedError("Metodo non implementato.")

    def decode(self, z):
        """
        Metodo per decodificare l'input z.

        Parametri:
        - z: L'input da decodificare.

        Restituisce:
        - x: L'output decodificato.
        """
        raise NotImplementedError("Metodo non implementato.")

    def encode_list(self, x_list):
        """
        Metodo per codificare una lista di elementi.

        Parametri:
        - x_list: La lista di elementi da codificare.

        Restituisce:
        - z_list: La lista di elementi codificati.
        """
        z_list = []
        for x in x_list:
            z = self.encode(x)
            z_list.append(z)
        return z_list

    def decode_list(self, z_list):
        """
        Metodo per decodificare una lista di elementi.

        Parametri:
        - z_list: La lista di elementi da decodificare.

        Restituisce:
        - x_list: La lista di elementi decodificati.
        """
        x_list = []
        for z in z_list:
            x = self.decode(z)
            x_list.append(x)
        return x_list
```
Nel caso di un formato tabellare, potremmo immaginare una classe del tipo:
```python
class TabularEncoder(Encoder):
    def __init__(self, encoding_dict):
        """
        Costruttore per la classe TabularEncoder.

        Parametri:
        - encoding_dict: Un dizionario contenente le descrizioni delle feature del dataset della black box.

        """
        self.encoding_dict = encoding_dict
```
